name: shfmt # you probably want to 'snapcraft register <name>'
version: "2.6.4" # just for humans, typically '1.2+git' or '1.3.2'
summary: A shell parser, formatter and interpreter (POSIX/Bash/mksh). # 79 char long summary
description: |
  "A shell parser, formatter and interpreter (POSIX/Bash/mksh)."

confinement: strict # use 'strict' once you have the right plugs and slots
grade: stable

parts:
  shfmt:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    prepare: |
      chmod +x prep/extractor.sh
      prep/extractor.sh
    organize:
      shfmt: bin/shfmt

apps:
  shfmt:
    command: bin/shfmt
    plugs:
      - home
      - network
